name: Nethermind Update

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
   - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Download Nethermind
      run: python download-latest-release.py
      env:
        CURRENT_VERSION: ${{ secrets.LAST_NETHERMIND_VERSION }}
    - if: ${{ env.DOWNLOADED_VERSION != '' }}
      uses: hmanzur/actions-set-secret@v2.0.1
      with:
        name: 'LAST_NETHERMIND_VERSION'
        value: ${{ env.DOWNLOADED_VERSION }}
        repository: credfeto/nethermind-updater
        token: ${{ secrets.SOURCE_PUSH_TOKEN }}
